name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Esegui la pipeline quando viene aggiornato il branch "main"

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout del codice
      - name: Checkout code
        uses: actions/checkout@v3

      # Login ad Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build e Push dell'immagine Docker su ACR
      - name: Build and push Docker image
        env:
          AZURE_REGISTRY: ${{ secrets.AZURE_REGISTRY }}
        run: |
          docker buildx build --platform linux/amd64 --tag ${{ secrets.AZURE_REGISTRY }}/resplash:latest --push --registry-login-server ${{ secrets.AZURE_REGISTRY }}.azurecr.io .

  deploy:
    name: Deploy to Azure Container Instances
    needs: build-and-push # Esegui il deploy solo dopo il completamento del build
    runs-on: ubuntu-latest

    steps:
      # Login ad Azure per il deploy
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Aggiorna il container su Azure Container Instances
      - name: Deploy to Azure Container Instances
        run: |
          az container create \
            --resource-group SistemiCloud \
            --name my-container \
            --image ${{ secrets.AZURE_REGISTRY }}/resplash:latest \
            --restart-policy Always \
            --cpu 1 \
            --memory 1.5
