name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Esegui la pipeline quando viene aggiornato il branch "main"

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Checkout del codice
    - name: Checkout code
      uses: actions/checkout@v3

    # Login ad Azure Container Registry (ACR)
    - name: Login to Azure Container Registry
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Build e Push dell'immagine Docker su ACR
    - name: Build and push Docker image
      env:
        AZURE_REGISTRY: ${{ secrets.AZURE_REGISTRY }}
        AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      run: |
        echo $AZURE_REGISTRY_PASSWORD | docker login $AZURE_REGISTRY -u $AZURE_REGISTRY_USERNAME --password-stdin
        docker build -t $AZURE_REGISTRY/resplash:latest .
        docker push $AZURE_REGISTRY/resplash:latest

  deploy:
    name: Deploy to Azure Container Instances
    needs: build-and-push  # Esegui il deploy solo dopo il completamento del build
    runs-on: ubuntu-latest

    steps:
    # Login ad Azure per il deploy
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Aggiorna il container su Azure Container Instances
    - name: Deploy to Azure Container Instances
      env:
        AZUR
